server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/base_b
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/serasa

app:
  ml-script-path: src/main/resources/scripts/calculate_score.py

management:
  endpoints:
    web:
      exposure:
        include: "*"
