spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

app:
  redis:
    ttl-minutes: 10 # Tempo de vida dos eventos