server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://desafio-postgres:5432/base_a
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  kafka:
#    bootstrap-servers: localhost:9092

security:
  oauth2:
    resource server:
      jwt:
        issuer-uri: http://localhost:9000

jasypt:
  encryptor:
    password: chave-secreta
    algorithm: PBEWithMD5AndDES

management:
  endpoints:
    web:
      exposure:
        include: "*"